# Generated by Django 5.2.7 on 2025-10-18 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session_Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_start', models.DateField()),
                ('session_end', models.DateField()),
            ],
        ),
    ]
